const cars = [
  {
    id: 1,
    name: "Ferrari A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 120190,
    year: 2018,
    rating: 4,
    thumbnail: require("../assets/cars/ferrari-20.jpg"),
  },
  {
    id: 2,
    name: "Mustang A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 240000,
    year: 2016,
    rating: 5,
    thumbnail: require("../assets/cars/mustang.jpg"),
  },
  {
    id: 3,
    name: "Ferrari Sport A2",
    model: "A2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 760000,
    year: 2019,
    rating: 5,
    thumbnail: require("../assets/cars/ferrari-sport.jpg"),
  },
  {
    id: 4,
    name: "Audi A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 400000,
    year: 2017,
    rating: 2,
    thumbnail: require("../assets/cars/audi-a4.jpg"),
  },
  {
    id: 5,
    name: "Bentley A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 350000,
    year: 2020,
    rating: 5,
    thumbnail: require("../assets/cars/bentley-a3.jpg"),
  },
  {
    id: 6,
    name: "Ferrari A1",
    model: "A1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 5670000,
    year: 2021,
    rating: 3,
    thumbnail: require("../assets/cars/ferrari-a1.jpg"),
  },
  {
    id: 7,
    name: "Ferrari A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 120190,
    year: 2018,
    rating: 4,
    thumbnail: require("../assets/cars/ferrari-20.jpg"),
  },
  {
    id: 8,
    name: "Mustang A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 240000,
    year: 2016,
    rating: 5,
    thumbnail: require("../assets/cars/mustang.jpg"),
  },
  {
    id: 9,
    name: "Ferrari Sport A2",
    model: "A2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 760000,
    year: 2019,
    rating: 5,
    thumbnail: require("../assets/cars/ferrari-sport.jpg"),
  },
  {
    id: 10,
    name: "Audi A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 400000,
    year: 2017,
    rating: 2,
    thumbnail: require("../assets/cars/audi-a4.jpg"),
  },
  {
    id: 11,
    name: "Bentley A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 350000,
    year: 2020,
    rating: 5,
    thumbnail: require("../assets/cars/bentley-a3.jpg"),
  },
  {
    id: 12,
    name: "Ferrari A1",
    model: "A1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 5670000,
    year: 2021,
    rating: 3,
    thumbnail: require("../assets/cars/ferrari-a1.jpg"),
  },
  {
    id: 13,
    name: "Ferrari A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 120190,
    year: 2018,
    rating: 4,
    thumbnail: require("../assets/cars/ferrari-20.jpg"),
  },
  {
    id: 14,
    name: "Mustang A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 240000,
    year: 2016,
    rating: 5,
    thumbnail: require("../assets/cars/mustang.jpg"),
  },
  {
    id: 15,
    name: "Ferrari Sport A2",
    model: "A2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 760000,
    year: 2019,
    rating: 5,
    thumbnail: require("../assets/cars/ferrari-sport.jpg"),
  },
  {
    id: 16,
    name: "Audi A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 400000,
    year: 2017,
    rating: 2,
    thumbnail: require("../assets/cars/audi-a4.jpg"),
  },
  {
    id: 17,
    name: "Bentley A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 350000,
    year: 2020,
    rating: 5,
    thumbnail: require("../assets/cars/bentley-a3.jpg"),
  },
  {
    id: 18,
    name: "Ferrari A1",
    model: "A1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 5670000,
    year: 2021,
    rating: 3,
    thumbnail: require("../assets/cars/ferrari-a1.jpg"),
  },
  {
    id: 19,
    name: "Ferrari A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 120190,
    year: 2018,
    rating: 4,
    thumbnail: require("../assets/cars/ferrari-20.jpg"),
  },
  {
    id: 20,
    name: "Mustang A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 240000,
    year: 2016,
    rating: 5,
    thumbnail: require("../assets/cars/mustang.jpg"),
  },
  {
    id: 21,
    name: "Ferrari Sport A2",
    model: "A2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 760000,
    year: 2019,
    rating: 5,
    thumbnail: require("../assets/cars/ferrari-sport.jpg"),
  },
  {
    id: 22,
    name: "Audi A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 400000,
    year: 2017,
    rating: 2,
    thumbnail: require("../assets/cars/audi-a4.jpg"),
  },
  {
    id: 23,
    name: "Bentley A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 350000,
    year: 2020,
    rating: 5,
    thumbnail: require("../assets/cars/bentley-a3.jpg"),
  },
  {
    id: 24,
    name: "Ferrari A1",
    model: "A1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 5670000,
    year: 2021,
    rating: 3,
    thumbnail: require("../assets/cars/ferrari-a1.jpg"),
  },
  {
    id: 25,
    name: "Ferrari A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 120190,
    year: 2018,
    rating: 4,
    thumbnail: require("../assets/cars/ferrari-20.jpg"),
  },
  {
    id: 26,
    name: "Mustang A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 240000,
    year: 2016,
    rating: 5,
    thumbnail: require("../assets/cars/mustang.jpg"),
  },
  {
    id: 27,
    name: "Ferrari Sport A2",
    model: "A2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 760000,
    year: 2019,
    rating: 5,
    thumbnail: require("../assets/cars/ferrari-sport.jpg"),
  },
  {
    id: 28,
    name: "Audi A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 400000,
    year: 2017,
    rating: 2,
    thumbnail: require("../assets/cars/audi-a4.jpg"),
  },
  {
    id: 29,
    name: "Bentley A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 350000,
    year: 2020,
    rating: 5,
    thumbnail: require("../assets/cars/bentley-a3.jpg"),
  },
  {
    id: 30,
    name: "Ferrari A1",
    model: "A1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 5670000,
    year: 2021,
    rating: 3,
    thumbnail: require("../assets/cars/ferrari-a1.jpg"),
  },
  {
    id: 31,
    name: "Ferrari A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 120190,
    year: 2018,
    rating: 4,
    thumbnail: require("../assets/cars/ferrari-20.jpg"),
  },
  {
    id: 32,
    name: "Mustang A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 240000,
    year: 2016,
    rating: 5,
    thumbnail: require("../assets/cars/mustang.jpg"),
  },
  {
    id: 33,
    name: "Ferrari Sport A2",
    model: "A2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 760000,
    year: 2019,
    rating: 5,
    thumbnail: require("../assets/cars/ferrari-sport.jpg"),
  },
  {
    id: 34,
    name: "Audi A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 400000,
    year: 2017,
    rating: 2,
    thumbnail: require("../assets/cars/audi-a4.jpg"),
  },
  {
    id: 35,
    name: "Bentley A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 350000,
    year: 2020,
    rating: 5,
    thumbnail: require("../assets/cars/bentley-a3.jpg"),
  },
  {
    id: 36,
    name: "Ferrari A1",
    model: "A1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 5670000,
    year: 2021,
    rating: 3,
    thumbnail: require("../assets/cars/ferrari-a1.jpg"),
  },
  {
    id: 37,
    name: "Ferrari A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 120190,
    year: 2018,
    rating: 4,
    thumbnail: require("../assets/cars/ferrari-20.jpg"),
  },
  {
    id: 38,
    name: "Mustang A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 240000,
    year: 2016,
    rating: 5,
    thumbnail: require("../assets/cars/mustang.jpg"),
  },
  {
    id: 39,
    name: "Ferrari Sport A2",
    model: "A2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 760000,
    year: 2019,
    rating: 5,
    thumbnail: require("../assets/cars/ferrari-sport.jpg"),
  },
  {
    id: 40,
    name: "Audi A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 400000,
    year: 2017,
    rating: 2,
    thumbnail: require("../assets/cars/audi-a4.jpg"),
  },
  {
    id: 41,
    name: "Bentley A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 350000,
    year: 2020,
    rating: 5,
    thumbnail: require("../assets/cars/bentley-a3.jpg"),
  },
  {
    id: 42,
    name: "Ferrari A1",
    model: "A1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 5670000,
    year: 2021,
    rating: 3,
    thumbnail: require("../assets/cars/ferrari-a1.jpg"),
  },
  {
    id: 43,
    name: "Ferrari A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 120190,
    year: 2018,
    rating: 4,
    thumbnail: require("../assets/cars/ferrari-20.jpg"),
  },
  {
    id: 44,
    name: "Mustang A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 240000,
    year: 2016,
    rating: 5,
    thumbnail: require("../assets/cars/mustang.jpg"),
  },
  {
    id: 45,
    name: "Ferrari Sport A2",
    model: "A2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 760000,
    year: 2019,
    rating: 5,
    thumbnail: require("../assets/cars/ferrari-sport.jpg"),
  },
  {
    id: 46,
    name: "Audi A4",
    model: "A4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 400000,
    year: 2017,
    rating: 2,
    thumbnail: require("../assets/cars/audi-a4.jpg"),
  },
  {
    id: 47,
    name: "Bentley A3",
    model: "A3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 350000,
    year: 2020,
    rating: 5,
    thumbnail: require("../assets/cars/bentley-a3.jpg"),
  },
  {
    id: 48,
    name: "Ferrari A1",
    model: "A1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    price: 5670000,
    year: 2021,
    rating: 3,
    thumbnail: require("../assets/cars/ferrari-a1.jpg"),
  },
];

export default cars;
